### ISSUE TITLE
NotImplementedError when running generate_rollout

### ISSUE THREAD

**Issue by agopal42** [uber-research/atari-model-zoo#5]
Traceback (most recent call last):
  File "/home/anand/IDSIA/mutual-information-keypoints/collect_atari_data.py", line 27, in <module>
    results = generate_rollout(m,min_frames=2500,max_frames=2500)
  File "/home/anand/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/atari_zoo/rollout.py", line 135, in generate_rollout
    obs = env.reset()
  File "/home/anand/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/gym/core.py", line 258, in reset
    return self.observation(observation)
  File "/home/anand/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/gym/core.py", line 265, in observation
    raise NotImplementedError
NotImplementedError

**Comment by akolobov** [comment]
Same problem. Any workarounds?

**Comment by agopal42** [comment]
It has to do with the API format for the methods like step(), reset(), render() etc. in atari_wrappers.py in atari_zoo which follow the old gym API format of using ._step(). By changing it to align with API format of the latest gym versions (0.15.3) by replacing the "._method_name()" with ".method_name()" and , it worked for me. Hope this helps!

**Comment by akolobov** [comment]
Yeah, thanks, just figured it out too! Instead of updating the model zoo code I went for installing gym==0.12.0 though.

**Comment by jal278** [comment]
Should now be fixed -- updated code according to @agopal42 's suggestion

**Comment by akolobov** [comment]
@jal278 , thank you!
